### ISSUE TITLE
document %checks

### ISSUE THREAD

**Issue by rattrayalex-stripe** [saltycrane/flow-cheatsheet#2]
Very hard to find docs for this feature anywhere 😄 

eg
```jsx
declare function isMap(maybeMap: mixed): boolean %checks(maybeMap instanceof Map);
```

**Comment by saltycrane** [comment]
Agree I couldn't find docs for `%checks` either. Google gave me these:

https://stackoverflow.com/questions/39456328/how-to-make-flow-understand-dynamic-code-that-uses-lodash-for-runtime-type-check
https://github.com/graphql/graphql-js/pull/695
https://github.com/facebook/flow/issues/2625
https://github.com/facebook/flow/issues/3048

¯\_(ツ)_/¯

**Comment by lll000111** [comment]
Another valid ticket closed without anything having been resolved. Great.

**Comment by lll000111** [comment]
Sorry, wrong project
