### ISSUE TITLE
Update cheatsheet for 0.53.0

### ISSUE THREAD

**Issue by johnhaley81** [saltycrane/flow-cheatsheet#4]
Flow v0.53.0 has a lot of changes to how types are handled in React. It would be awesome to have a cheat sheet for those too :)

**Comment by saltycrane** [comment]
Hi John, I updated the cheat sheet for v0.53.1. Take a look: https://www.saltycrane.com/flow-type-cheat-sheet/latest/

**Comment by johnhaley81** [comment]
Looks great! Thanks for the awesome reference!
