### ISSUE TITLE
Synthetic events missing > 0.54.0

### ISSUE THREAD

**Issue by rosskevin** [saltycrane/flow-cheatsheet#5]
I'm not sure why, I checked [release notes](https://github.com/facebook/flow/releases), but it seems that the `Synthetic*Event`s are no longer present in cheatsheets > 0.54.0

**Comment by saltycrane** [comment]
Thanks for letting me know! It looks like a separate `lib/react-dom.js` file was extracted out after version 0.54.0. It should be fixed now... take a look at the new "React DOM" section here: https://www.saltycrane.com/flow-type-cheat-sheet/latest/#lib/react-dom.js
