### ISSUE TITLE
What to call the "private" types?

### ISSUE THREAD

**Issue by pe3** [saltycrane/flow-cheatsheet#6]
Could they be called combinators?

**Comment by saltycrane** [comment]
I don't have a good understanding of what combinator means, but it doesn't seem like all of the types with a `$` in the name would fit that meaning.

**Comment by pe3** [comment]
I was mainly thinking on the ones under `Built-in "private" types` and the idea of combining things. From [Haskell wiki](https://wiki.haskell.org/Combinator): 
> Usually there is some type T, some functions for constructing "primitive" values of type T, and some "combinators" which can combine values of type T in various ways to build up more complex values of type T.

T would be the more core Flow types and combinators would be used to construct more complex types.

But it was just a thought and more of a question for you if I had been able to recognize combinators. I'm still in the process of learning types in general.

**Comment by saltycrane** [comment]
Thanks for the explanation of combinator. That definition makes sense. I don't see the types with the `$` being more combinator-like than the types without the `$` though. A lot of times the types without the `$` use the types with the `$`.

I don't know of a good term for them either. I think it more of a question for the Flow team and I would just use whatever they call it.

**Comment by pe3** [comment]
Yep. Should we close the issue then?

**Comment by saltycrane** [comment]
Yes, closing...
