### ISSUE TITLE
How to import these types?

### ISSUE THREAD

**Issue by murrayju** [saltycrane/flow-cheatsheet#8]
I've been pulling my hair out trying to figure out the proper way to get flow to annotate built in node types. Unfortunately googling terms like `Server` and `https` don't really get you anywhere. I did stumble across this very helpful repo though!

I'm trying to do:
```
// @flow
import type { Server } from 'https';
```

But flow isn't happy:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/server/AppServer.js:2:15

Cannot import Server because there is no Server export in https.

     1│ // @flow
     2│ import type { Server } from 'https';
```

I'm still trying to understand how flow type declarations are supposed to work, but it seems to me that the [linked source](https://github.com/facebook/flow/blob/v0.75.0/lib/node.js#L1205) wouldn't work because it is missing the `export` keyword. Is that right, or is there some way to get flow to recognize these types and I just have it configured wrong?

**Comment by murrayju** [comment]
Ok, I've answered my own question. These types are just available for use without any import. Just use them, they work.

**Comment by saltycrane** [comment]
I was wondering if this was the case, but I didn't get to verify. (I have not done much node.js programming.) It threw me off a bit that the react module behaves differently. Happy to hear you solved it!
